// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using apidemoproj.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace apidemoproj.Data
{
    public partial interface IapidemoContextProcedures
    {
        Task<int> uspLogErrorAsync(OutputParameter<int?> ErrorLogID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> uspPrintErrorAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
